#!/bin/bash

set -euo pipefail

gqlgen_dir=$(pwd)
cd $(mktemp -d)
go mod init inittest
printf '// +build tools\npackage tools\nimport _ "github.com/00security/gqlgen"' | gofmt > tools.go
go mod tidy
go mod edit -replace=github.com/00security/gqlgen="$gqlgen_dir"
go mod tidy

go get github.com/00security/gqlgen

if { go run github.com/00security/gqlgen init 2>&1 >&3 3>&- | grep '^' >&2; } 3>&1; then
    echo "gqlgen init failed validation"
    exit 125
fi
